# Generated by Django 4.1.7 on 2023-03-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("how", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="code",
            field=models.TextField(default=""),
        ),
    ]
